version: "3.7"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8081:8081"

  postgres:
    image: postgres:11.13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD: root
      - POSTGRES_USER: postgres



